name: Docker Image CI

on:
  workflow_run:
    workflows: Run Test Suite for CRM API
    branches: main
    types: completed

jobs:
  push-to-registry:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: cmbdk/crm-api:latest

      - name: Push README to Docker Hub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: cmbdk/crm-api
          provider: docker_hub
          short_description: 'REST API created using Flask connected to a PostgreSQL DB that runs locally'
          readme_file: 'README.md'
