name: Run Test Suite for CRM API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo code
        uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v4
        with:
          python-version: 3.12

      - name: Run tests
        env:
            FLASK_APP: run.py
            ENV_TYPE: 'Testing'
            CONFIG_TYPE: config.TestingConfig
            ISOLATION_LEVEL: 'SERIALIZABLE'
        run: |
          pipenv install
          pipenv run python3 -m pytest
