name: Run Test Suite for CRM API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Run tests
        env:
            FLASK_APP: run.py
            ENV_TYPE: Testing
            CONFIG_TYPE: config.TestingConfig
            ISOLATION_LEVEL: SERIALIZABLE
        run: |
          flask test
