name: Run Unit Tests via Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        user: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: crm_api_db
        ports:
        - [5432:5432]
        # setting health checks to wait until the service is running
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Check out the repo code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
        pip install pipenv
        pipenv install

      - name: Run unit tests
        env: 
          DATABASE_URL: 'postgres://postgres:root@localhost:${{ job.services.postgres.ports[5432] }}crm_api_db'
        run: |
        python3 app.py
        pytest tests/crm_test.py
